//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputSystem/InputPlayer.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputPlayer : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputPlayer()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputPlayer"",
    ""maps"": [
        {
            ""name"": ""PlayerMap"",
            ""id"": ""a012d03a-6d74-42ac-ab24-7a649dbf649a"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""216b8070-8e65-42e7-97c3-6d9b1848d2c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Haut"",
                    ""type"": ""Value"",
                    ""id"": ""c7eaea8c-0f70-4ced-8ac8-312b15990bb7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Bas"",
                    ""type"": ""Value"",
                    ""id"": ""d6ef3b74-dd8c-4579-aa99-c5dfded7905d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Gauche"",
                    ""type"": ""Value"",
                    ""id"": ""dc8cda6e-bcde-41e2-af97-f041d1e1ccfa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Droite"",
                    ""type"": ""Value"",
                    ""id"": ""3f434aca-2819-4873-ac68-aca67cdb1a4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d365d93e-7342-4723-b6dd-7a2cf31f5218"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04a66930-c6e3-46c1-9f84-62abb39b571b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Haut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31857b77-694c-4c5f-bc24-43b35848faf7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bas"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a94cee4-2b2a-44e3-b488-e1aad3cbab03"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gauche"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a92dc1cc-1f79-4d54-9490-0c9aef6beffc"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Droite"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerMap
        m_PlayerMap = asset.FindActionMap("PlayerMap", throwIfNotFound: true);
        m_PlayerMap_Jump = m_PlayerMap.FindAction("Jump", throwIfNotFound: true);
        m_PlayerMap_Haut = m_PlayerMap.FindAction("Haut", throwIfNotFound: true);
        m_PlayerMap_Bas = m_PlayerMap.FindAction("Bas", throwIfNotFound: true);
        m_PlayerMap_Gauche = m_PlayerMap.FindAction("Gauche", throwIfNotFound: true);
        m_PlayerMap_Droite = m_PlayerMap.FindAction("Droite", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMap
    private readonly InputActionMap m_PlayerMap;
    private IPlayerMapActions m_PlayerMapActionsCallbackInterface;
    private readonly InputAction m_PlayerMap_Jump;
    private readonly InputAction m_PlayerMap_Haut;
    private readonly InputAction m_PlayerMap_Bas;
    private readonly InputAction m_PlayerMap_Gauche;
    private readonly InputAction m_PlayerMap_Droite;
    public struct PlayerMapActions
    {
        private @InputPlayer m_Wrapper;
        public PlayerMapActions(@InputPlayer wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_PlayerMap_Jump;
        public InputAction @Haut => m_Wrapper.m_PlayerMap_Haut;
        public InputAction @Bas => m_Wrapper.m_PlayerMap_Bas;
        public InputAction @Gauche => m_Wrapper.m_PlayerMap_Gauche;
        public InputAction @Droite => m_Wrapper.m_PlayerMap_Droite;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMapActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerMapActions instance)
        {
            if (m_Wrapper.m_PlayerMapActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnJump;
                @Haut.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnHaut;
                @Haut.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnHaut;
                @Haut.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnHaut;
                @Bas.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnBas;
                @Bas.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnBas;
                @Bas.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnBas;
                @Gauche.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnGauche;
                @Gauche.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnGauche;
                @Gauche.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnGauche;
                @Droite.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnDroite;
                @Droite.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnDroite;
                @Droite.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnDroite;
            }
            m_Wrapper.m_PlayerMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Haut.started += instance.OnHaut;
                @Haut.performed += instance.OnHaut;
                @Haut.canceled += instance.OnHaut;
                @Bas.started += instance.OnBas;
                @Bas.performed += instance.OnBas;
                @Bas.canceled += instance.OnBas;
                @Gauche.started += instance.OnGauche;
                @Gauche.performed += instance.OnGauche;
                @Gauche.canceled += instance.OnGauche;
                @Droite.started += instance.OnDroite;
                @Droite.performed += instance.OnDroite;
                @Droite.canceled += instance.OnDroite;
            }
        }
    }
    public PlayerMapActions @PlayerMap => new PlayerMapActions(this);
    public interface IPlayerMapActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnHaut(InputAction.CallbackContext context);
        void OnBas(InputAction.CallbackContext context);
        void OnGauche(InputAction.CallbackContext context);
        void OnDroite(InputAction.CallbackContext context);
    }
}
